### PR TITLE
add support of getting ip from ip138 && last ip

### PR DESCRIPTION
**Pull request by hengbo12345**
1. most of cases around cannot get their IPs of Internet from network cards directly. It should be more  convenient to use a public service here such as ip138 or ip.taobao.com.

2. record of last ip can be useful to reduce the frequency of request to dnspod.

### CODE REVIEW

**Comment by ProfFan** [comment]
Thank you for your PR. To me there are two problems before we can merge this:
1. There should be a switch between using an query-based IP lookup and normal interface-based lookup in the config file.
2. `last.ip` should be put into a proper place like `/tmp`. We do not assume write access to any directory.

**Comment by hengbo12345** [comment]
ok, i'll improve it later.

在 2017-01-26 11:35:30，"Fan Jiang" <notifications@github.com> 写道：


Thank you for your PR. To me there are two problems before we can merge this:

There should be a switch between using an query-based IP lookup and normal interface-based lookup in the config file.
last.ip should be put into a proper place like /tmp. We do not assume write access to any directory.

**Comment by wzhy90** [comment]
https://www.dnspod.cn/docs/records.html#record-info
There is an API to get the last IP

**Comment by hengbo12345** [comment]
As the doc said, the result of this api contains only dns record, but not the ip address of where the request comes from.


Thanks


在2017年03月03 17时22分, "wzhy90"<notifications@github.com>写道:



https://www.dnspod.cn/docs/records.html#record-info
There is an API to get the last IP

**Pull request closed without merging**
